- name: Add repository for nodejs
  become: yes
  yum_repository:
    name: rpm_repo_node
    description: rpm YUM repo
    baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
    gpgcheck: no
- name: Installing nodejs {{node_version}}
  become: yes
  yum: name=nodejs-{{node_version}} state=present