- hosts: webserver
  vars_files: 
  - config.yml
  tasks:
    - name: role node js for webserver
      include_role: 
        name: nodejs
      vars:
        nodejs_version: 7.2.0
    - name: Install nginx 
      become: yes
      yum: name="nginx" state=present
    - name: Set the port for nginx in the conf file.
      become: yes
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/default.conf
    - name: Restart the Nginx
      become: yes
      service: 
        name: nginx 
        state: started 
        enabled: yes
- hosts: devserver
  tasks:
    - name: role node js
      include_role: 
        name: nodejs
      vars:
        nodejs_version: 7.10.0
    - debug: "msg={{nodejs_version}}" 