- hosts: webserver
  vars_files:
   - config.yml
  tasks:
    - name: nginx
      include_role: 
        name: nginx
    - name: role node js for webserver
      include_role: 
        name: nodejs
      vars:
        node_version: "{{node_version_web_server}}"
- hosts: devserver
  vars_files:
   - config.yml
  tasks:
    - name: role node js
      include_role: 
        name: nodejs
      vars:
        node_version: "{{node_version_dev_server}}"