- hosts: webserver
  vars_files:
   - configs/config_web.yml
  tasks:
    - name: webserver role
      include_role: 
        name: webserver

- hosts: devserver
  vars_files:
   - configs/config_dev.yml
  tasks:
    - name: devserver role
      include_role: 
        name: devserver